In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split

In [3]:
data = pd.read_csv("dataset.csv")

In [4]:
data.shape

(100, 11)

In [5]:
data.head(1)

Patient ID  Age  Blood Pressure  Cholesterol Levels  Heart Rate   BMI  \
0         101   65             130                 250          72  28.0   

                             Diagnosis  \
0  Hypertension with high cholesterol.   

                                      Treatment Plan  Recovery Status  \
0  Medication: Lisinopril (blood pressure), Stati...  Active Recovery   

        Medication Type Follow-up Requirement  
0  Lisinopril, Statins.            Quarterly.

In [6]:
meddata=data[['Age','Blood Pressure','Cholesterol Levels','Heart Rate','BMI','Diagnosis']]
meddata.head(1)

Age  Blood Pressure  Cholesterol Levels  Heart Rate   BMI  \
0   65             130                 250          72  28.0   

                             Diagnosis  
0  Hypertension with high cholesterol.

In [7]:
meddata['Diagnosis'] = meddata['Diagnosis'].apply(
    lambda x: 1 if any(condition in x for condition in ['Hypertension', 'Obesity', 'Overweight']) else 0
)

C:\Users\SUPRATIM NAG\AppData\Local\Temp\ipykernel_4220\2310464088.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meddata['Diagnosis'] = meddata['Diagnosis'].apply(


In [9]:
meddata.head()

Age  Blood Pressure  Cholesterol Levels  Heart Rate   BMI  Diagnosis
0   65             130                 250          72  28.0          1
1   42             110                 150          76  24.0          0
2   58             140                 200          80  30.0          0
3   71             160                 220          88  32.0          0
4   35             120                 180          74  27.0          1

In [10]:
X = meddata.drop('Diagnosis', axis=1)
y = meddata['Diagnosis']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [13]:
#process1

num_trees=10
model=AdaBoostClassifier(n_estimators=num_trees)

In [18]:
kfold=model_selection.KFold(n_splits=6)
results=model_selection.cross_val_score(model,X_train,y_train,cv=kfold)

C:\Users\SUPRATIM NAG\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\SUPRATIM NAG\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\SUPRATIM NAG\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\SUPRATIM NAG\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
 

In [19]:
print(results)

[0.71428571 0.57142857 0.61538462 0.76923077 0.61538462 0.61538462]


In [20]:
print(results.mean())

0.6501831501831502


In [21]:
X = meddata.drop('Diagnosis', axis=1)
y = meddata['Diagnosis']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [22]:
#process2
model=AdaBoostClassifier(n_estimators=num_trees)
model.fit(X_train,y_train)

C:\Users\SUPRATIM NAG\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier(n_estimators=10)

In [24]:
y_pred=model.predict(X_test)

In [25]:
y_pred

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1],
      dtype=int64)

In [26]:
model.score(X_test,y_test)

0.65

In [28]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.67      0.83      0.74        12
           1       0.60      0.38      0.46         8

    accuracy                           0.65        20
   macro avg       0.63      0.60      0.60        20
weighted avg       0.64      0.65      0.63        20

[[10  2]
 [ 5  3]]
