In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv("dataset.csv")

In [3]:
data.shape

(100, 11)

In [4]:
data.head(1)

Patient ID  Age  Blood Pressure  Cholesterol Levels  Heart Rate   BMI  \
0         101   65             130                 250          72  28.0   

                             Diagnosis  \
0  Hypertension with high cholesterol.   

                                      Treatment Plan  Recovery Status  \
0  Medication: Lisinopril (blood pressure), Stati...  Active Recovery   

        Medication Type Follow-up Requirement  
0  Lisinopril, Statins.            Quarterly.

In [5]:
meddata=data[['Age','Blood Pressure','Cholesterol Levels','Heart Rate','BMI','Diagnosis']]
meddata.head(1)

Age  Blood Pressure  Cholesterol Levels  Heart Rate   BMI  \
0   65             130                 250          72  28.0   

                             Diagnosis  
0  Hypertension with high cholesterol.

In [6]:
meddata['Diagnosis'] = meddata['Diagnosis'].apply(
    lambda x: 1 if any(condition in x for condition in ['Hypertension', 'Obesity', 'Overweight']) else 0
)

C:\Users\SUPRATIM NAG\AppData\Local\Temp\ipykernel_16284\2310464088.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meddata['Diagnosis'] = meddata['Diagnosis'].apply(


In [7]:
meddata.head()

Age  Blood Pressure  Cholesterol Levels  Heart Rate   BMI  Diagnosis
0   65             130                 250          72  28.0          1
1   42             110                 150          76  24.0          0
2   58             140                 200          80  30.0          0
3   71             160                 220          88  32.0          0
4   35             120                 180          74  27.0          1

In [8]:
X = meddata.drop('Diagnosis', axis=1)
y = meddata['Diagnosis']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [9]:
model=GaussianNB()

In [10]:
kfold=model_selection.KFold(n_splits=6)
results=model_selection.cross_val_score(model,X_train,y_train,cv=kfold)

In [11]:
print(results)

[0.5        0.71428571 0.61538462 0.46153846 0.38461538 0.61538462]


In [12]:
print(results.mean())

0.5485347985347986


In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [14]:
model=GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [23]:
y_pred=model.predict(X_test)
y_pred

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1],
      dtype=int64)

In [24]:
model.score(X_test,y_test)

0.55

In [26]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[9 5]
 [4 2]]
              precision    recall  f1-score   support

           0       0.69      0.64      0.67        14
           1       0.29      0.33      0.31         6

    accuracy                           0.55        20
   macro avg       0.49      0.49      0.49        20
weighted avg       0.57      0.55      0.56        20

